version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./kerminal:/app/kerminal
    environment:
      - ENVIRONMENT=development
    command: python -m kerminal.api.main
  